### ISSUE TITLE
How to get the joint_train.npy

### ISSUE THREAD

**Issue by dumyy** [Smilels/TeachNet_Teleoperation#1]
There seem to be some commands missing about data processing between data generation and model training in your readme.md.
Could you provide them?
Thank you!

**Comment by Smilels** [comment]
Hi, I updated the readme.md. Could you check whether it is clear enough for you? Please be careful about the location of your dataset.

**Comment by dumyy** [comment]
@Smilels  Thanks! I will have a try.

**Comment by dumyy** [comment]
@Smilels . I have tried to run the command `python utils/seg_depth.py`. 
I find that the simulated shadow depth map can be cropped and resized well after I changed the params  of the function `seg_hand_depth`.
But the human depth map can't be cropped well, which always has a human body background. 
I want to know that if the human depth map is cropped by the pose label or only using the function `seg_hand_depth`  in the file `seg_depth.py`.
Thanks!

**Comment by Smilels** [comment]
Sorry for taking two days to get back with you.
You're right. You need to run "ros/src/shadow_teleop/scripts/depth_image_crop.py" first which crop human hand images to 100*100 first then run seg_depth,py. I will update README.md again.
Good luck.

**Comment by dumyy** [comment]
I have got the right cropped images! 
Thanks.
